config/routes.rb
Rails.application.routes.draw do
  resources :matches do
    resources :shuffles, only: :index, module: :matches
  end
  resources :players, only: %i[show create destroy] do
    resources :pays, module: :players
  end
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/match.rb
class Match < ApplicationRecord
  has_many :players, dependent: :destroy

  validates :place, :time, presence: true
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :match

  validates :full_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @current_match = Match.last
    @players = @current_match.players if @current_match
    @new_player = Player.new
  end
end

app/controllers/matches/shuffles_controller.rb
class Matches::ShufflesController < ApplicationController
  def index
    @match = Match.find(params[:match_id])
    @max_players = params[:max_players]&.to_i || 6
    @teams = @match.players.shuffle.each_slice(@max_players).to_a
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: %i[ show edit update destroy ]

  # GET /matches or /matches.json
  def index
    @matches = Match.order(created_at: :desc)
  end

  # GET /matches/1 or /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  # POST /matches or /matches.json
  def create
    @match = Match.new(match_params)

    respond_to do |format|
      if @match.save
        format.html { redirect_to match_url(@match), notice: "Match was successfully created." }
        format.json { render :show, status: :created, location: @match }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1 or /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to match_url(@match), notice: "Match was successfully updated." }
        format.json { render :show, status: :ok, location: @match }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /matches/1 or /matches/1.json
  def destroy
    @match.destroy

    respond_to do |format|
      format.html { redirect_to matches_url, notice: "Match was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def match_params
      params.require(:match).permit(:place, :time)
    end
end

app/controllers/players/pays_controller.rb
class Players::PaysController < ApplicationController
  def create
    @player = Player.find(params[:player_id])
    @player.touch(:pay_at)

    redirect_to match_url(@player.match_id), notice: 'El Jugador ha hecho su pago'
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[destroy]

  def create
    @player = Player.new(player_params)

    if @player.save
      redirect_to root_path, notice: 'Player was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    match_id = @player.match_id
    @player.destroy

    redirect_to match_url(match_id), notice: 'Jugador Eliminado'
  end

  private

  def player_params
    params.require(:player).permit(:full_name, :match_id)
  end

  def set_player
    @player = Player.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches/shuffles_helper.rb
module Matches::ShufflesHelper
end

app/views/home/index.html.erb
<% if @current_match %>
  <div class="m-auto md:max-w-[480px]" />
    <h3 class="text-sm lg:text-lg flex justify-between capitalize mb-6">
      <div><%= l(@current_match.time, format: '%A %d - %I:%M %p', locale: :es) %> </div>
      <div>
        <%= @current_match.place %>
      </div>
    </h3>
    <%= link_to 'Sortear equipos', match_shuffles_url(@current_match), class: "block bg-green-100 hover:bg-green-50 text-green-700 px-3 py-2 rounded-md text-sm font-medium text-center" %>

    <ol class="border rounded-md divide-y  overflow-auto h-[400px] my-6">
      <% @players.each do |player| %>
        <li class="py-2 flex items-center">
          <span class="ml-5 text-xs md:text-sm truncate"> <%= player.full_name %> </span>
        </li>
      <% end  %>
    </ol>

    <%= form_with model: @new_player do |form| %>
      <div class="flex">
        <%= form.hidden_field :match_id, value: @current_match.id %>
        <%= form.text_field :full_name, placeholder: 'Ingresa tu nombre', class: 'appearance-none block w-full px-3 py-3 border border-gray-300 rounded-md placeholder-gray-400 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 transition duration-150 ease-in-out sm:text-sm sm:leading-5', required: true %>
        <button type="button" class="md:min-w-[60px] flex items-center justify-center py-2 px-3 ml-2 border border-transparent text-sm font-medium rounded-md text-white bg-green-600 hover:bg-green-500 focus:outline-none focus:border-green-700 focus:shadow-outline-green active:bg-green-700 transition duration-150 ease-in-out">
          <%= form.submit 'Go' %>
        </button>
      </div>
    <% end %>
  </div>
<% else %>
  <div>No hay partidos que mostrar :(</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cojos</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>
  <body class="antialiased font-sans">
    <% if notice.present? %>
      <%= render partial: "shared/alert" %>
    <% end %>
    <main class="container mx-auto p-8">
      <%= yield %>
    </main>
  </body>
</html>

app/views/matches/_form.html.erb
<%= form_with(model: match) do |form| %>
  <% if match.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(match.errors.count, "error") %> prohibited this match from being saved:</h2>

      <ul>
        <% match.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :place, style: "display: block" %>
    <%= form.text_field :place %>
  </div>

  <div>
    <%= form.label :time, style: "display: block" %>
    <%= form.datetime_field :time %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/matches/_match.html.erb
<div id="<%= dom_id match %>" class="mb-6">
  <p>
    <strong>Place:</strong>
    <%= match.place %>
  </p>

  <p>
    <strong>Time:</strong>
    <%= match.time %>
  </p>

  <%= link_to "Ver partido", match, class: "text-blue-600 font-semibold hover:text-blue-500" %> |
  <%= link_to "Editar partido", edit_match_path(match) %>
</div>

app/views/matches/edit.html.erb
<h1>Editing match</h1>

<%= render "form", match: @match %>

<br>

<div>
  <%= link_to "Show this match", @match %> |
  <%= link_to "Back to matches", matches_path %>
</div>

app/views/matches/index.html.erb
<div class="sm:flex justify-between mb-8">
  <h1 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:leading-9 sm:truncate">
    Matches
  </h1>
  <%= link_to "Nuevo partido", new_match_path, class: 'inline-block mt-3 sm:m-0 text-center items-center px-4 py-2 border border-transparent text-sm leading-5 font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition ease-in-out duration-150' %>
</div>

<div>
  <% @matches.each do |match| %>
    <%= render match %>
  <% end %>
</div>

app/views/matches/new.html.erb
<h1>New match</h1>

<%= render "form", match: @match %>

<br>

<div>
  <%= link_to "Back to matches", matches_path %>
</div>

app/views/matches/show.html.erb
<%= link_to "Volver a los partidos", matches_path %>
<hr>

<div class="sm:flex mt-4">
  <div class="flex justify-between sm:w-56 sm:mr-4 sm:pr-4 sm:border-r sm:border-gray-100">
    <h2 class="text-xl sm:text-3xl"><%= @match.place %></h2>
    <%= link_to "Editar", edit_match_path(@match), class: 'text-blue-600' %>
  </div>
  <div class="flex-grow mt-8 sm:mt-0">
    <div class="flex justify-between items-center">
      <h2 class="my-4 text-lg">Juradores</h2>
      <%= link_to "Agregar jugador", edit_match_path(@match), class: 'text-blue-600' %>
    </div>
    <% @match.players.each do |player| %>
      <div class="sm:flex justify-between flex-row mb-2 group p-3 rounded-md text-sm hover:bg-gray-50">
        <div class="flex">
          <div class="w-[150px]"><%= player.full_name %></div>
          <% if player.pay_at %>
            <span class="inline-flex items-center justify-center px-2 py-1 mr-2 text-xs font-bold leading-none text-green-100 bg-green-600 rounded-full">
              Pagó
            </span>
          <% end %>
        </div>

        <div class="flex mt-4 sm:mt-0">
          <% unless player.pay_at %>
            <%= button_to "Pagar", player_pays_url(player), method: :post, class: "mr-4 text-orange-500" %>
          <% end %>
          <%= button_to "Eliminar", player, method: :delete %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/matches/shuffles/index.html.erb
<main class="-mt-8">
  <div class="text-lg font-bold flex justify-center">Sortear Equipos</div>

  <section class="">
    <div class="my-5">
      <%= form_with url: match_shuffles_url(@match), method: :get do |form| %>
        <%= form.label :max_players, "Max. de jugadores", style: "font-size: 14px" %>
        <%= form.number_field :max_players, value: @max_players, required: true, min: 4, max: 12, style: "width: 5rem"%>
        <button type="button" class="px-3 py-2 border border-transparent text-sm md:text-base font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700">
          <%= form.submit "Go" %>
        </button>
      <% end %>
    </div>

    <div class="mb-5">
      <% @teams.each_with_index do |team, index| %>
        <h3 class="my-2 font-semibold underline">Equipo <%= index + 1 %></h3>
        <ol class="border border-gray-300 rounded-md divide-y divide-gray-300">
          <% team.each do |player| %>
            <li class="py-2 flex items-center">
              <span class="ml-5 text-xs md:text-sm truncate"> <%= player.full_name %> </span>
            </li>
          <% end  %>
        </ol>
      <% end  %>
    </div>

    <button type="button" class="px-3 py-2 border border-transparent text-sm md:text-base font-medium rounded-md text-white bg-yellow-600 hover:bg-yellow-700">
      <%= link_to "Volver", root_path %>
    </button>
  </section>
</main>

app/views/shared/_alert.html.erb
<div class="bg-blue-600 mb-8">
  <div class="max-w-7xl mx-auto py-3 px-3 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between flex-wrap">
      <div class="w-0 flex-1 flex items-center">
        <p class="ml-3 font-medium text-white truncate">
          <%= notice %>
        </p>
      </div>
      <div class="order-2 flex-shrink-0 sm:order-3 sm:ml-3">
        <button type="button" class="-mr-1 flex p-2 rounded-md hover:bg-blue-500 focus:outline-none focus:ring-2 focus:ring-white sm:-mr-2">
          <span class="sr-only">Dismiss</span>
          <!-- Heroicon name: outline/x -->
          <svg class="h-6 w-6 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  </div>
</div>